apiVersion: v1
kind: Pod
metadata:
  name: mysql-{{ .Release.Name }}-{{ .Chart.Version }}
  labels:
    run: mysql
spec:
  containers:
  - name: mysql
    image: mysql        
    env:
    - name: MYSQL_DATABASE
      value: {{ .Values.db.databaseName }}
    - name: MYSQL_USER
      value: {{ .Values.db.userName }}
    - name: MYSQL_PASSWORD
      value: {{ .Values.db.password }}
    - name: MYSQL_ROOT_PASSWORD
      value: {{ .Values.db.rootPassword }}
    ports:
      - containerPort: {{ .Values.db.containerPort }}
    volumeMounts:
      - name: mysql-initdb
        mountPath: /docker-entrypoint-initdb.d
      - name: mysql-config
        mountPath: /etc/mysql/conf.d
  volumes:
    - name: mysql-initdb
      configMap:
        name: mysql-initdb-config
    - name: mysql-config
      configMap:
        name: mysql-utf8-config