apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: NodePort # 추후 clusterIP 로 변경할 수도 있음
  selector:
    run: mysql
  ports:
    - port: {{ .Values.db.containerPort }}
      nodePort: {{ .Values.db.externalPort }}
      name: http
