apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort
  selector:
    app: flask
  ports:
    - port: {{ .Values.flask.containerPort }}
      nodePort: {{ .Values.flask.externalPort }} # curl -X GET $(minikube ip):31112/
      name: http