apiVersion: v1
kind: Pod
metadata:
  name: flask
  labels:
    run: flask
spec:
  serviceAccountName: kjy
  containers:
    - name: flask
      image: 192.1.4.75:5000/flask-server:v0.1.8
      imagePullPolicy: Always
      ports:
        - containerPort: 3307
      env:
        - name: DB_IP
          value: '192.168.99.100' # DB pod 이 떠있는 node 의 IP
        - name: DB_PORT
          value: '31111' # DB pod 의 mapping service port
        - name: DB_USER
          value: testuser
        - name: DB_PASSWORD
          value: testpassword
        - name: DB_DATABASE
          value: testdb
