apiVersion: v1
kind: Pod
metadata:
  name: flask
  labels:
    run: flask
spec:
  serviceAccountName: kjy
  containers:
    - name: flask
      image: 192.1.4.75:5000/flask-server:v0.1.10 # 이미지 URL, NAME, TAG 를 환경에 맞게 수정
      imagePullPolicy: Always
      ports:
        - containerPort: 3307
      env:
        - name: DB_IP
          value: '192.168.99.100' # DB pod 이 떠있는 node 의 IP 으로 수정
        - name: DB_PORT
          value: '31111'
        - name: DB_USER
          value: testuser
        - name: DB_PASSWORD
          value: testpassword
        - name: DB_DATABASE
          value: testdb
        - name: AE_MODEL_IMAGE_URL
          value: '192.1.4.75:5000/model-ae:v0.1.9' # ae model 의 이미지 URL, NAME, TAG 를 환경에 맞게 수정
      volumeMounts:
        - mountPath: "/input"
          name: in-storage
        - mountPath: "/output"
          name: out-storage
  volumes:
    - name: in-storage
      persistentVolumeClaim:
        claimName: pvc-input
    - name: out-storage
      persistentVolumeClaim:
        claimName: pvc-output
