apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort # 추후 clusterIP 로 변경할 수도 있음
  selector:
    run: flask
  ports:
    - port: 3307
      nodePort: 31112
      name: http
