#!/bin/bash

REPOSITORY_URL=localhost:5000
VERSION=v0.1.5
IMAGE_NAME=model-ae

docker build -t $IMAGE_NAME:$VERSION .
docker tag $IMAGE_NAME:$VERSION $REPOSITORY_URL/$IMAGE_NAME:$VERSION

docker push $REPOSITORY_URL/$IMAGE_NAME:$VERSION