#!/bin/bash

#REPOSITORY_URL=localhost:5000
REPOSITORY_URL=ghcr.io/anencore94
VERSION=v0.0.3
IMAGE_NAME=flask-server

docker build -t $IMAGE_NAME:$VERSION .
docker tag $IMAGE_NAME:$VERSION $REPOSITORY_URL/$IMAGE_NAME:$VERSION

docker push $REPOSITORY_URL/$IMAGE_NAME:$VERSION
