apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort
  selector:
    app: flask
  ports:
    - port: 3307
      nodePort: 31112 # curl -X GET $(minikube ip):31112/
      name: http