apiVersion: batch/v1
kind: Job
metadata:
  name: job-ae
  labels:
    mlmodel: ae
spec:
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: kjy
      restartPolicy: Never
      containers:
        - name: ae
          image: 192.1.4.75:5000/model-ae:v0.1.9
          imagePullPolicy: Always
          env:
            - name: LEARNING_RATE
              value: '0.005'   # TODO pod env 에서 str 말고 int, float 으로 받을 수 있는 방법
            - name: EPOCH
              value: '25'
            - name: EXPERIMENT_ID
              value: 'ex11'
            - name: OUTPUT_MOUNT_POINT
              value: '/output'
          volumeMounts:
            - mountPath: "/output"
              name: out-storage
            - mountPath: "/input"
              name: in-storage
      volumes:
      - name: in-storage
        persistentVolumeClaim:
          claimName: pvc-input
      - name: out-storage
        persistentVolumeClaim:
          claimName: pvc-output
