apiVersion: v1
kind: Pod
metadata:
  name: ae
  labels:
    mlmodel: ae
spec:
  serviceAccountName: kjy
  restartPolicy: Never
  containers:
    - name: ae
      image: 192.1.4.75:5000/model-ae:v0.1.4
      imagePullPolicy: Always
      env:
        - name: LEARNING_RATE
          value: "0.005"   # TODO pod env 에서 str 말고 int, float 으로 받을 수 있는 방법
        - name: EPOCH
          value: "25"
      ports:
        - containerPort: 3307
      volumeMounts:
        - mountPath: "/output"
          name: out-storage
        - mountPath: "/input"
          name: in-storage
  volumes:
    - name: in-storage
      hostPath: # 추후 local pvc 생성 후 사용하도록 변경
        path: /hosthome/kjy/input/ # input data 가 저장되어 있는 host node 의 경로
        type: Directory
    - name: out-storage
      hostPath:
        path: /mnt/sda1/data/ # 출력을 저장할 host node 의 경로
        type: Directory
