apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-output
  labels:
    data: output
spec:
  storageClassName: sample
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  local:
    path: /mnt/sda1/data/output # 이것만 원하는 node 의 경로로 수정 필요
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube # 이것만 원하는 node 의 hostname 으로 수정 필요