kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-input
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: sample
  selector:
    matchLabels:
      data: input
