db:
  databaseName: testdb
  userName: testuser
  password: testpassword
  rootPassword: testpassword
  containerPort: 3306
  externalPort: 31111
flask:
  imageName: ghcr.io/anencore94/flask-server
  imageTag: v1.0.7
  containerPort: 3307
  mysqlIP: 192.168.39.169 # minikube ip (since nodeport service)
#  externalPort: 31112
