name: Mrx On Boarding

on:
  push:
    branches: [ mrx-onboarding ]
    paths-ignore:
      - mrx-on-boarding-chart # helm chart 를 업데이트하는 커밋은 argocd 에 맡기고 github action 파이프라인에서는 제외

env:
  REPOSITORY_URL: ghcr.io/${{ github.repository_owner }}
  VERSION: v0.1.4 # TODO tag 로 변환
  IMAGE_NAME: flask-server

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Branch Checkout
        uses: actions/checkout@v2
      - name: Mock Test
        run: echo "Nothing to Unit Test"
  build_and_push:
    needs: unit_test # Ensure test job passes before pushing image.
    runs-on: ubuntu-latest
    if: github.event_name == 'push' # TODO 필요?
    steps:
      - name: Branch Checkout
        uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build Docker Image
        run: |
          cd ./backend # since source code hardcoding
          docker build . --file ./Dockerfile -t $REPOSITORY_URL/$IMAGE_NAME:$VERSION
      - name: Check if build successful
        run: docker images | grep $IMAGE_NAME
      - name: Docker push to ghcr
        run: docker push $REPOSITORY_URL/$IMAGE_NAME:$VERSION
  change_chart_and_commit: # TODO values.yaml 고치고, commit 때리기
    needs: [unit_test, build_and_push]
    runs-on: ubuntu-latest
    steps:
      - name: Branch Checkout
        uses: actions/checkout@v2
      - name: Change values.yaml with New Image Tag
        run: echo "hi"
      - name: Git Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: New Image Released
      - name: Mock Test
        run: echo "Re-Deploy"