name: Mrx On Boarding

on:
  push:
    branches: [ mrx-onboarding  ]

env:
  REPOSITORY_URL: ghcr.io/${{ github.repository_owner }}
  VERSION: v0.1.3 # TODO tag 로 변환
  IMAGE_NAME: flask-server

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Branch Checkout
        uses: actions/checkout@v2
      - name: Mock Test
        run: echo "Nothing to Unit Test"
  build_and_push:
    needs: unit_test # Ensure test job passes before pushing image.
    runs-on: ubuntu-latest
    if: github.event_name == 'push' # TODO 필요?
    steps:
      - name: Branch Checkout
        uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker Image
        run: |
          cd ./backend # since source code hardcoding
          docker build . --file ./Dockerfile -t $REPOSITORY_URL/$IMAGE_NAME:$VERSION
      - name: Check if build successful
        run: docker images | grep $IMAGE_NAME
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Docker push to ghcr
        run: docker push $REPOSITORY_URL/$IMAGE_NAME:$VERSION
  re_deploy:
    needs: [unit_test, build_and_push]
    runs-on: ubuntu-latest
    steps:
      - name: Branch Checkout
        uses: actions/checkout@v2
      - name: Mock Test
        run: echo "Re-Deploy"
  api_test:
    needs: [unit_test, build_and_push, re_deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Branch Checkout
        uses: actions/checkout@v2
      - name: Mock Test
        run: echo "Nothing to API Test"