name: Mrx On Boarding

on:
  push:
    branches: [ mrx-onboarding ]
    paths-ignore:
      - mrx-on-boarding-chart # helm chart 를 업데이트하는 커밋은 argocd 에 맡기고 github action 파이프라인에서는 제외

env:
  REPOSITORY_URL: ghcr.io/${{ github.repository_owner }}
  VERSION: v1.0.2 # TODO tag 로 변환
  IMAGE_NAME: flask-server

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Branch Checkout
        uses: actions/checkout@v2
        with:
          ref: mrx-onboarding
      - name: Mock Test
        run: echo "Nothing to Unit Test"
  build_and_push:
    needs: unit_test # Ensure test job passes before pushing image.
    runs-on: ubuntu-latest
    steps:
      - name: Branch Checkout
        uses: actions/checkout@v2
        with:
          ref: mrx-onboarding
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build Docker Image # change directory since hardcoded-source code
        working-directory: backend
        run: |
          docker build . --file ./Dockerfile -t ${{ env.REPOSITORY_URL }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
      - name: Check if build successful
        run: docker images | grep $IMAGE_NAME
      - name: Docker push to ghcr
        run: docker push ${{ env.REPOSITORY_URL }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
  change_chart_and_commit:
    needs: [unit_test, build_and_push]
    runs-on: ubuntu-latest
    steps:
      - name: Branch Checkout
        uses: actions/checkout@v2
        with:
          ref: mrx-onboarding
      - name: Change values.yaml with New Image Tag
        run: |
          mv ./mrx-on-boarding-chart/values.yaml ./mrx-on-boarding-chart/values-orig.yaml
          sed 's|imageTag: v*.*.*|imageTag: ${{ env.VERSION }}|' ./mrx-on-boarding-chart/values-orig.yaml > ./mrx-on-boarding-chart/values.yaml
          rm ./mrx-on-boarding-chart/values-orig.yaml
      - name: Git Add, Commit and Push
        uses: github-actions-x/commit@v2.8
        with:
          github-token: ${{ secrets.PERSONAL_TOKEN }}
          push-branch: mrx-onboarding
          commit-message: '[New Release] ${{ env.REPOSITORY_URL }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }} has been released!'
          rebase: 'true'
          force-add: 'true'
          files: ./mrx-on-boarding-chart/values.yaml
          name: anencore94
          email: anencore94@gmail.com
      - name: Mock Test
        run: echo "Re-Deploy"