name: Mrx On Boarding

on:
  push:
    branches: [ mrx-onboarding  ]

env:
  REPOSITORY_URL: ghcr.io/${{ github.repository_owner }}
  VERSION: v0.0.3 # TODO tag 로 변환
  IMAGE_NAME: flask-server

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Mock Test
        run: echo "Nothing to Test"
  build_and_push:
    needs: test # Ensure test job passes before pushing image.
    runs-on: ubuntu-latest
    if: github.event_name == 'push' # TODO 필요?
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: |
          cd ./backend # since source code hardcoding
          docker build . --file ./Dockerfile -t $REPOSITORY_URL/$IMAGE_NAME:$VERSION
      - name: Check if build successful
        run: docker images | grep $IMAGE_NAME
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Docker push to ghcr
        run: docker push $REPOSITORY_URL/$IMAGE_NAME:$VERSION
